# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  vss-ui:
    environment:
      APP_SOCKET_APPEND: ${CONFIG_SOCKET_APPEND:-CONFIG_OFF}
      APP_SUMMARY_FEATURE: ${SUMMARY_FEATURE:-FEATURE_OFF}
      APP_SEARCH_FEATURE: ${SEARCH_FEATURE:-FEATURE_ON}

  pipeline-manager:
    depends_on:
      vdms-vector-db:
        condition: service_started
      vdms-dataprep:
        condition: service_started
      vclip-embedding-ms:
        condition: service_healthy
      video-search:
        condition: service_started
    environment:
      SEARCH_ENDPOINT: ${VS_ENDPOINT}
      SEARCH_DATAPREP_ENDPOINT: ${VDMS_DATAPREP_ENDPOINT}
      SUMMARY_FEATURE: ${SUMMARY_FEATURE:-FEATURE_OFF}
      SEARCH_FEATURE: ${SEARCH_FEATURE:-FEATURE_ON}

  video-search:
    image: ${REGISTRY:-}video-search:${TAG:-latest}
    build:
      context: ../search-ms
      dockerfile: docker/Dockerfile
    depends_on:
      vdms-vector-db:
        condition: service_started
      minio-service:
        condition: service_healthy
      vdms-dataprep:
        condition: service_started
      vclip-embedding-ms:
        condition: service_healthy
    ipc: host
    ports:
      - "${VS_HOST_PORT}:8000"
    environment:
      no_proxy: ${no_proxy},${VCLIP_HOST},${VDMS_DATAPREP_HOST},${MINIO_HOST},${VDMS_VDB_HOST},${PM_HOST}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      VDMS_VDB_HOST: ${VDMS_VDB_HOST}
      VDMS_VDB_PORT: 55555
      VCLIP_EMBEDDINGS_ENDPOINT: ${VCLIP_ENDPOINT}
      VCLIP_EMBEDDINGS_MODEL_NAME: ${VCLIP_MODEL}
      VCLIP_EMBEDDINGS_NUM_FRAMES: ${VCLIP_NUM_FRAMES}
      INDEX_NAME: ${VS_INDEX_NAME}
      WATCH_DIRECTORY: ${VS_WATCHER_DIR}
      DEBOUNCE_TIME: ${VS_DEBOUNCE_TIME}
      DELETE_PROCESSED_FILES: ${VS_DELETE_PROCESSED_FILES}
      VS_INITIAL_DUMP: ${VS_INITIAL_DUMP}
      MINIO_API_PORT: 80
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      VIDEO_UPLOAD_ENDPOINT: ${VDMS_PIPELINE_MANAGER_UPLOAD}
      VDMS_BUCKET: ${VDMS_BUCKET}
      CHUNK_DURATION: ${VS_DEFAULT_CLIP_DURATION}
    restart: unless-stopped
    volumes:
      - "${VS_WATCHER_DIR:-/dev/null}:/tmp/watcher-dir"
    networks:
      - vs_network

  vdms-vector-db:
    image: intellabs/vdms:v2.10.0
    ipc: host
    environment:
      - OVERRIDE_images_path=db/images
      - OVERRIDE_descriptors_path=db/descriptors
      - OVERRIDE_blobs_path=db/blobs
      - OVERRIDE_pmgd_path=db/graph
    ports:
      - "${VDMS_VDB_HOST_PORT}:55555"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/v1/health_check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - vs_network

  vdms-dataprep:
    image: ${REGISTRY:-}vdms-dataprep:${TAG:-latest}
    hostname: vdms-dataprep
    environment:
      no_proxy: ${no_proxy},${VDMS_VDB_HOST},${VCLIP_HOST},${MINIO_HOST}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      APP_HOST: vdms-dataprep
      VDMS_VDB_HOST: ${VDMS_VDB_HOST}
      VDMS_VDB_PORT: 55555
      DB_COLLECTION: ${VS_INDEX_NAME}
      MULTIMODAL_EMBEDDING_ENDPOINT: ${VCLIP_ENDPOINT}
      MULTIMODAL_EMBEDDING_MODEL_NAME: ${VCLIP_MODEL}
      MULTIMODAL_EMBEDDING_NUM_FRAMES: ${VCLIP_NUM_FRAMES}
      MINIO_ENDPOINT: ${MINIO_HOST}:80
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_SECURE: false
    ports:
      - "${VDMS_DATAPREP_HOST_PORT}:8000"
    depends_on:
      vdms-vector-db:
        condition: service_started
      vclip-embedding-ms:
        condition: service_healthy
      minio-service:
        condition: service_healthy
    volumes:
      - data-prep:/tmp/dataprep
    networks:
      - vs_network

  vclip-embedding-ms:
    image: ${REGISTRY:-}multimodal-embedding-serving:${TAG:-latest}
    ports:
      - "${VCLIP_HOST_PORT}:8000"
    ipc: host
    environment:
      no_proxy: ${no_proxy},${MINIO_HOST},${VDMS_DATAPREP_HOST}
      no_proxy_env: ${no_proxy},${MINIO_HOST},${VDMS_DATAPREP_HOST}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      MODEL_NAME: ${VCLIP_MODEL}
      DEFAULT_START_OFFSET_SEC: ${VCLIP_START_OFFSET_SEC}
      DEFAULT_CLIP_DURATION: ${VCLIP_CLIP_DURATION}
      DEFAULT_NUM_FRAMES: ${VCLIP_NUM_FRAMES}
      EMBEDDING_USE_OV: ${VCLIP_USE_OV}
      EMBEDDING_DEVICE: ${VCLIP_DEVICE}
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID-1000} 
      - ${VIDEO_GROUP_ID-44}    
      - ${RENDER_GROUP_ID-1002}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 5s
    networks:
      - vs_network
    volumes:
      - ov-models:/home/appuser/.cache/huggingface
      - data-prep:/tmp/dataprep
      - ov-models:/app/ov-models

volumes:
  ov-models:
    external: true
  data-prep:
    external: true
