multimodalembeddingms:
  enabled: true
multimodaldataprep:
  enabled: true
vdmsvectordb:
  enabled: true
vectorretriever:
  enabled: true
videosearch:
  enabled: true

global:
  # vdmsIndexName is the DB Index or DB Collection name used by VDMS Vector DB.
  vdmsIndexName: "video_frame_embeddings"

pipelinemanager:
  env:
    SEARCH_DATAPREP_TIMEOUT_MS: "600000"
    SEARCH_FEATURE: "FEATURE_ON"

searchui:
  enabled: true
  name: search-ui
  feature:
    summary: "FEATURE_OFF"
    search: "FEATURE_ON"
    mux: "ATOMIC"
