multimodalembeddingms:
  enabled: true
multimodaldataprep:
  enabled: true
vdmsvectordb:
  enabled: true
vectorretriever:
  enabled: true
videosearch:
  enabled: true
rabbitmq:
  enabled: true
ovms:
  enabled: true
videoingestion:
  enabled: true
audioanalyzer:
  enabled: true

global:
  # vdmsIndexName is the DB Index or DB Collection name used by VDMS Vector DB.
  vdmsIndexName: "video_summary_embeddings"

pipelinemanager:
  env:
    SEARCH_DATAPREP_TIMEOUT_MS: "600000"
    SUMMARY_FEATURE: "FEATURE_ON"
    SEARCH_FEATURE: "FEATURE_ON"

summaryui:
  enabled: true
  name: unified-ui
  feature:
    summary: "FEATURE_ON"
    search: "FEATURE_ON"
    mux: "SUMMARY_SEARCH"

searchui:
  enabled: false