apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
data:
  default.conf: |+
    # Config for nginx mounted to /etc/nginx/conf.d in the pod

    server {
        listen       80;
        listen  [::]:80;

        client_max_body_size 500M;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300; 

        # Add specific location for assets to properly handle static files like fonts
        location /assets/ {
            proxy_pass http://{{ .Values.videosummaryui.name }}:{{ .Values.videosummaryui.service.port }}/assets/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location / {
            proxy_pass http://{{ .Values.videosummaryui.name }}:{{ .Values.videosummaryui.service.port }};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
        
        location /manager/ {
            proxy_pass http://{{ .Values.videoSummaryManager.name }}:{{ .Values.videoSummaryManager.service.targetPort }}/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        location /ws/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            proxy_pass http://{{ .Values.videoSummaryManager.name }}:{{ .Values.videoSummaryManager.service.targetPort }}/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /minio/ {
            proxy_pass http://{{ .Values.minioServer.name }}:{{ .Values.minioServer.service.port }}/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
            }
  
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "video-summarization.labels" . | nindent 4 }}
    app: {{ include "nginx.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "nginx.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.fullname" . }}
    spec:
      containers:
      - image: nginx:1.27.1
        imagePullPolicy: {{ .Values.videoSummaryManager.image.pullPolicy }}
        name: nginx
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-volume
        ports:
        - containerPort: 80
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "nginx.fullname" . }}-config
        name: nginx-config-volume
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.global.env.UI_NODEPORT }}
  selector:
    app: {{ include "nginx.fullname" . }}
  type: NodePort
