# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

"""Pass-through provider adapter.

A pass-through provider forwards a request body verbatim to a backing service
and returns the response untouched — used for OpenAI/Cohere-compatible services
the router does not itself implement (audio transcription/speech, embeddings,
rerank, OCR).

Unlike chat providers, a pass-through provider is NOT a ``ProviderAdapter``: it
has no chat/stream/list_models and must never be a routing candidate. It is
configured exactly like any other provider (an entry in the ``providers:`` list)
whose ``type`` names the service, e.g.::

    - name: "ocr-backend"
      type: "ocr"
      model: "ocr"
      settings:
        endpoint: "http://localhost:8002"
        timeout: 600

Adding a new service kind is a single entry in ``PASSTHROUGH_SERVICES`` below —
it drives the reserved type set, the generated route (see
``src/api/v1/passthrough.py``), and the forwarding behavior here.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass

import httpx
from fastapi import HTTPException, Request
from fastapi.responses import JSONResponse, Response

from src.config.base import ProviderConfig


logger = logging.getLogger(__name__)


# Response headers regenerated by our server rather than copied from upstream.
_HOP_BY_HOP = ("content-length", "content-encoding", "transfer-encoding", "connection")

# Sane default request timeout (seconds) when a pass-through provider omits
# ``settings.timeout``. Never leave it unset: ``httpx`` treats ``timeout=None``
# as "no timeout", so a hung backend would pin a worker forever. Generous
# because cold-start services (e.g. OCR) can be slow on the first request.
DEFAULT_TIMEOUT = 600.0


@dataclass(frozen=True)
class PassthroughSpec:
    """Describes one pass-through service kind."""

    route: str          # FastAPI route path exposed by the gateway, e.g. "/v1/ocr"
    upstream: str       # subpath appended to endpoint when it lacks the tail
    binary: bool = False  # True -> return raw bytes (e.g. TTS audio), else JSON


# Single source of truth for pass-through services. Keys are the provider
# ``type`` values that select PassthroughProvider. To add a service (e.g.
# "vision"), add one entry here — no other code changes required.
PASSTHROUGH_SERVICES: dict[str, PassthroughSpec] = {
    "transcription": PassthroughSpec("/v1/audio/transcriptions", "/v1/audio/transcriptions"),
    "tts": PassthroughSpec("/v1/audio/speech", "/v1/audio/speech", binary=True),
    "embeddings": PassthroughSpec("/v1/embeddings", "/v1/embeddings"),
    "rerank": PassthroughSpec("/v1/rerank", "/v1/rerank"),
    "ocr": PassthroughSpec("/v1/ocr", "/v1/ocr"),
}

# The reserved provider ``type`` values that route to PassthroughProvider.
PASSTHROUGH_TYPES = frozenset(PASSTHROUGH_SERVICES)


class PassthroughProvider:
    """Forwards requests verbatim to a backing service.

    Built by ``create_provider`` for any provider whose ``type`` is in
    ``PASSTHROUGH_TYPES``. The orchestrator keeps these out of chat routing and
    exposes them by service via ``passthrough_for``.
    """

    def __init__(self, provider_config: ProviderConfig):
        self.name = provider_config.name
        self.service = provider_config.type
        if self.service not in PASSTHROUGH_SERVICES:
            # Defensive: create_provider only builds us for known types.
            raise ValueError(f"Unknown pass-through service type: {self.service!r}")
        self.spec = PASSTHROUGH_SERVICES[self.service]

        settings = provider_config.settings or {}
        auth = settings.get("auth") or {}

        self.model = provider_config.model
        self.endpoint = settings.get("endpoint")
        # Bound the request; fall back to DEFAULT_TIMEOUT rather than leaving it
        # unset (which httpx interprets as no timeout at all).
        _timeout = settings.get("timeout")
        self.timeout = float(_timeout) if _timeout else DEFAULT_TIMEOUT
        # Auth mirrors LitellmProvider: scheme in {"bearer" (default), "api_key",
        # "none"}. For "none" we never authenticate. custom_headers are always
        # merged in. These are only applied when configured; by default the
        # client's own headers are forwarded untouched.
        self.auth_scheme = (auth.get("scheme") or "bearer").lower()
        self.api_key = None if self.auth_scheme == "none" else auth.get("api_key")
        self.custom_headers = dict(auth.get("custom_headers") or {})

    def _upstream_url(self) -> str:
        """Resolve the full upstream URL, appending the service subpath if absent."""
        if not self.endpoint:
            raise HTTPException(
                status_code=503,
                detail=f"{self.service} service has no endpoint configured",
            )
        url = self.endpoint
        tail = self.spec.upstream.lstrip("/")  # e.g. "v1/ocr"
        # Match the legacy behavior: accept an endpoint that already points at
        # the service path (ends with the last path segment(s)) and use it as-is.
        if url.rstrip("/").endswith(tail) or url.rstrip("/").endswith(tail.split("/")[-1]):
            return url
        return url.rstrip("/") + self.spec.upstream

    def _request_headers(self, request: Request) -> dict:
        """Forward the client's headers, dropping host, injecting configured auth."""
        headers = dict(request.headers)
        headers.pop("host", None)
        if self.api_key and self.auth_scheme in ("bearer", "api_key"):
            if self.auth_scheme == "bearer":
                headers["authorization"] = f"Bearer {self.api_key}"
            else:  # api_key
                headers["api-key"] = self.api_key
        if self.custom_headers:
            # Configured headers win over client-supplied ones.
            headers.update(self.custom_headers)
        return headers

    @staticmethod
    def _filter_response_headers(response: httpx.Response) -> dict:
        return {k: v for k, v in response.headers.items() if k.lower() not in _HOP_BY_HOP}

    async def forward(self, request: Request) -> Response:
        """Forward ``request`` to the backing service and return its response.

        Reads the full request body once (buffers in memory — fine for typical
        payloads; switch to streaming if very large uploads become a concern),
        forwards it with the client headers, and returns the upstream response
        untouched. Raises ``HTTPException`` (504/502/500) on transport errors so
        the calling endpoint stays a thin wrapper.
        """
        url = self._upstream_url()
        try:
            body = await request.body()
            headers = self._request_headers(request)

            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, content=body, headers=headers)

            filtered = self._filter_response_headers(response)

            if self.spec.binary:
                # Binary payload (e.g. TTS audio) — return bytes untouched.
                return Response(
                    content=response.content,
                    status_code=response.status_code,
                    headers=filtered,
                    media_type=response.headers.get("content-type", "application/octet-stream"),
                )

            # JSON services. Upstream normally returns JSON (success or error
            # detail); fall back to raw text if it ever doesn't, rather than 500.
            try:
                content = response.json()
            except Exception:
                return JSONResponse(
                    content={"detail": response.text},
                    status_code=response.status_code,
                    headers=filtered,
                )
            return JSONResponse(
                content=content,
                status_code=response.status_code,
                headers=filtered,
            )

        except httpx.TimeoutException as exc:
            logger.error(f"Timeout forwarding to {self.service} service: {url}")
            raise HTTPException(status_code=504, detail=f"{self.service} service timeout") from exc
        except httpx.RequestError as exc:
            logger.error(f"Error forwarding to {self.service} service: {exc}")
            raise HTTPException(
                status_code=502, detail=f"Failed to reach {self.service} service: {exc}"
            ) from exc
        except HTTPException:
            raise
        except Exception as exc:
            logger.error(f"Unexpected error in {self.service} pass-through: {exc}")
            raise HTTPException(status_code=500, detail=f"Internal server error: {exc}") from exc

    async def health_check(self) -> bool:
        """Reachability probe against the configured endpoint.

        With no ``endpoint`` there is nothing to probe: warn and skip rather than
        report a verdict. Otherwise a bare GET on the base endpoint — any HTTP
        response means reachable; only a transport error is unhealthy.
        """
        if not self.endpoint:
            logger.warning(
                "no health check probe available for pass-through provider '%s' "
                "(no endpoint to probe); skipping",
                self.name,
            )
            return True
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                await client.get(self.endpoint)
            return True
        except Exception:
            return False
