global:
  report_dir: 'reports'
  input_profiles_path: 'profiles/profiles.yaml'  # Reference to external input profiles file
  metrics_collector: 'intel/metrics-manager:2026.1.0'  # Metrics Manager image used as the resource-metrics collector
  jaeger_url: 'traces url' # https://<url or IP>/api/traces

apis:
  stream_log:
    enabled: true
    service_name: 'chatqna'
    endpoints:
      chat: '8102/v1/chatqna/chat'
      document: '8102/v1/chatqna/documents'
    input_profile: 'chatqna_wsf'  # Reference to input profile
  
  document:
    enabled: false
    endpoints:
      document: '8102/v1/chatqna/documents'
    input_profile: 'document_medium'  # Reference to input profile
