global:
  report_dir: 'reports'
  input_profiles_path: 'profiles/profiles.yaml'  # Reference to external input profiles file
  metrics_collector: 'intel/metrics-manager:2026.1.0'  # Metrics Manager image used as the resource-metrics collector


apis:
  video_summary:
    enabled: true
    service_name: 'video'
    endpoints:
      upload: '12345/manager/videos'
      summary: '12345/manager/summary'
      states: '12345/manager/states'
      telemetry: '9766/v1/telemetry'
    input_profile: 'video_summary_injection'  # Reference to input profile
  

