global:
  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  keeppvc: false

replicaCount: 1

modeldownload:
  name: model-download
  image:
    registry: "intel/"
    tag: 2026.2.0-ww31
    pullPolicy: IfNotPresent

  startupConfig:
    enabled: false
    config:
      download_path: models
      parallel_downloads: false
      models:
        - name: <Model-name>
          hub: huggingface
          type: embeddings
        - name: <Model-name>
          hub: openvino
          type: llm
          is_ovms: true
          config:
            precision: int8
            device: CPU
            cache_size: 10

  readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
    
  env:
    HUGGINGFACEHUB_API_TOKEN: ""
    MAX_UPLOAD_SIZE_MB: "500"
    UPLOAD_CHUNK_SIZE_KB: "8"
    GETI_WORKSPACE_ID: ""
    GETI_HOST: ""
    GETI_TOKEN: ""
    GETI_SERVER_API_VERSION: "v1"
    GETI_SERVER_SSL_VERIFY: "False"
    ENABLED_PLUGINS: "huggingface"   #Comma separated list of plugins to enable, or "all"
    OVMS_RELEASE_TAG: "v2025.4.1"
    #HLS pre-configured parameters
    HLS_3D_POSE_CHECKPOINT_URL: "https://storage.openvinotoolkit.org/repositories/open_model_zoo/public/2022.1/human-pose-estimation-3d-0001/human-pose-estimation-3d.tar.gz"
    HLS_ECG_BASE_URL: "https://raw.githubusercontent.com/Einse57/OpenVINO_sample/master/ai-ecg-master"
    HLS_RPPG_MODEL_URL: "https://github.com/xliucs/MTTS-CAN/raw/main/mtts_can.hdf5"

  
  gpu:
    enabled: false
    key: ""
  
  affinity:  #Optional: Provide node hostname label on which model download needs to be scheduled.
    enabled : false
    key: kubernetes.io/hostname
    value: 
            
  service:
    type: NodePort
    nodePort: 
    port: 8000
