global:
  huggingface:
    apiToken:  # Set this during installation
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy: 
  EMBEDDING_MODEL_NAME:  # Set this during installation

ovms:
  name: ovms-embedding
  image:
    repository: openvino/model_server
    tag: "2025.0"
    Gputag: "2025.0-gpu"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: v2/health/ready
      port: 8400
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8400
    targetPort: 8400
  # scriptconfigmap: ovms-configmap.yaml
  env:
    WEIGHT_FORMAT: "int8"
    model_directory_name: "converted_model"
  script:
    name: "ovms-embed-model-preparation"

