# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "Application"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: chatqna-app
version: 1.2.1
description: "Chat Q&A Sample Application"
helmRegistry: "docker-hub"
chartName: "intel/chat-question-and-answer"

chartVersion: "1.2.1"
defaultProfile: "ovms"

profiles:
  - name: "ovms"
    displayName: "ovms"
    valuesFileName: "chatqna-values-ovms.yaml"
    parameterTemplates:
      - name: global.proxy.http_proxy
        displayName: "Http proxy"
        type: string
        default: ""
      - name: global.proxy.https_proxy
        displayName: "Https proxy"
        type: string
        default: ""
      - name: global.proxy.no_proxy
        displayName: "No proxy"
        type: string
        default: "localhost,127.0.0.1"
      - name: global.huggingface.apiToken
        displayName: "Huggingface API Token"
        type: string
        mandatory: true
      - name: global.UI_NODEPORT
        displayName: "Static UI NodePort"
        type: string
        mandatory: true
      - name: global.POSTGRES_USER
        displayName: "Postgres username"
        type: string
        mandatory: true
      - name: global.POSTGRES_PASSWORD
        displayName: "Postgres password"
        type: string
        secret: true
        mandatory: true
      - name: global.MINIO_ROOT_USER
        displayName: "Minio username"
        type: string
        mandatory: true
      - name: global.MINIO_ROOT_PASSWORD
        displayName: "MINIO password"
        type: string
        secret: true
        mandatory: true
      - name: global.LLM_MODEL
        displayName: "LLM Model name"
        type: string
        default: ""
        mandatory: true
      - name: global.EMBEDDING_MODEL_NAME
        displayName: "Embedding model name"
        type: string
        default: ""
        mandatory: true
      - name: global.RERANKER_MODEL
        displayName: "Reranker model name"
        type: string
        default: ""
        mandatory: true
      - name: global.OTLP_ENDPOINT
        displayName: "OTLP Endpoint"
        type: string
        default: ""
      - name: global.OTLP_ENDPOINT_TRACE
        displayName: "OTLP Endpoint Trace"
        type: string
        default: ""
      - name: global.ovmsEmbeddinggpuService.enabled
        displayName: "OVMS Embedding GPU Service"
        type: boolean
        suggestedValues: ["false", "true"]
        mandatory: true
      - name: global.gpu.enabled
        displayName: Enable GPU Device
        type: boolean
        suggestedValues: ["false", "true"]
        mandatory: true
      - name: global.gpu.key
        displayName: GPU Node Label Key
        type: string
        default: ""
      - name: global.gpu.device
        displayName: GPU Device
        type: string
        default: ""
  - name: "vllm"
    valuesFileName: "chatqna-values-vllm.yaml"
    parameterTemplates:
      - name: global.proxy.http_proxy
        displayName: "Http proxy"
        type: string
        default: ""
      - name: global.proxy.https_proxy
        displayName: "Https proxy"
        type: string
        default: ""
      - name: global.proxy.no_proxy
        displayName: "No proxy"
        type: string
        default: "localhost,127.0.0.1"
      - name: global.huggingface.apiToken
        displayName: "Huggingface API Token"
        type: string
        mandatory: true
      - name: global.UI_NODEPORT
        displayName: "Static UI NodePort"
        type: string
        mandatory: true
      - name: global.POSTGRES_USER
        displayName: "Postgres username"
        type: string
        mandatory: true
      - name: global.POSTGRES_PASSWORD
        displayName: "Postgres password"
        type: string
        secret: true
        mandatory: true
      - name: global.MINIO_ROOT_USER
        displayName: "Minio username"
        type: string
        mandatory: true
      - name: global.MINIO_ROOT_PASSWORD
        displayName: "MINIO password"
        type: string
        secret: true
        mandatory: true
      - name: global.LLM_MODEL
        displayName: "LLM Model name"
        type: string
        default: ""
        mandatory: true
      - name: global.EMBEDDING_MODEL_NAME
        displayName: "Embedding model name"
        type: string
        default: ""
        mandatory: true
      - name: global.RERANKER_MODEL
        displayName: "Reranker model name"
        type: string
        default: ""
        mandatory: true
      - name: global.OTLP_ENDPOINT
        displayName: "OTLP Endpoint"
        type: string
        default: ""
      - name: global.OTLP_ENDPOINT_TRACE
        displayName: "OTLP Endpoint Trace"
        type: string
        default: ""
  - name: "tgi"
    valuesFileName: "chatqna-values-tgi.yaml"
    parameterTemplates:
      - name: global.proxy.http_proxy
        displayName: "Http proxy"
        type: string
        default: ""
      - name: global.proxy.https_proxy
        displayName: "Https proxy"
        type: string
        default: ""
      - name: global.proxy.no_proxy
        displayName: "No proxy"
        type: string
        default: "localhost,127.0.0.1"
      - name: global.huggingface.apiToken
        displayName: "Huggingface API Token"
        type: string
        mandatory: true
      - name: global.UI_NODEPORT
        displayName: "Static UI NodePort"
        type: string
        mandatory: true
      - name: global.POSTGRES_USER
        displayName: "Postgres username"
        type: string
        mandatory: true
      - name: global.POSTGRES_PASSWORD
        displayName: "Postgres password"
        type: string
        secret: true
        mandatory: true
      - name: global.MINIO_ROOT_USER
        displayName: "Minio username"
        type: string
        mandatory: true
      - name: global.MINIO_ROOT_PASSWORD
        displayName: "MINIO password"
        type: string
        secret: true
        mandatory: true
      - name: global.LLM_MODEL
        displayName: "LLM Model name"
        type: string
        default: ""
        mandatory: true
      - name: global.EMBEDDING_MODEL_NAME
        displayName: "Embedding model name"
        type: string
        default: ""
        mandatory: true
      - name: global.RERANKER_MODEL
        displayName: "Reranker model name"
        type: string
        default: ""
        mandatory: true
      - name: global.OTLP_ENDPOINT
        displayName: "OTLP Endpoint"
        type: string
        default: ""
      - name: global.OTLP_ENDPOINT_TRACE
        displayName: "OTLP Endpoint Trace"
        type: string
        default: ""