#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "Time Series Analytics Microservice - Unit Testing"
run-name: "Time Series Analytics Microservice - Unit Testing (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  workflow_dispatch:
  workflow_call: 

jobs:
  timeseries-unit-test:
    name: Timeseries Unit Test
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
      with:
          path: timeseries
          persist-credentials: false
    - name: Run unit tests
      run: |
        cd "${{ github.workspace }}"
        cd ./microservices/time-series-analytics
        echo "Running unit tests"
        ./tests/run_tests.sh
        coverage=$(grep 'TOTAL' /tmp/unit-test-results.txt | awk '{print $4}')
        # Extract test summary
        summary=$(grep -Eo '[0-9]+ (passed|failed|skipped)' /tmp/unit-test-results.txt)
        # Calculate total number of test cases
        total_tests=$(echo "$summary" | awk '{sum += $1} END {print sum}')
        # Extract number of passed tests
        passed_tests=$(echo "$summary" | grep 'passed' | awk '{print $1}')
        # Extract number of failed tests
        failed_tests=$(echo "$summary" | grep 'failed' | awk '{print $1}')
        # Print results
        echo "Coverage: $coverage" >> $GITHUB_STEP_SUMMARY
        echo "Total tests: $total_tests" >> $GITHUB_STEP_SUMMARY
        echo "Passed tests: $passed_tests" >> $GITHUB_STEP_SUMMARY
        echo "Failed tests: $failed_tests" >> $GITHUB_STEP_SUMMARY
    - name: Upload HTML unit test coverage to Github
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-coverage
        path: /tmp/htmlcov
    - name: Upload XML unit test coverage to Github
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-report
        path: /tmp/report.txt